/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testing;

/**
 *
 * @author musyo
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLandlord = new javax.swing.JButton();
        jTenant = new javax.swing.JButton();
        jVisitor = new javax.swing.JButton();
        jCaretaker = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("ELDERO RENTALS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(91, 33, 330, 42);

        jLandlord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLandlord.setText("Landlord");
        jLandlord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLandlordActionPerformed(evt);
            }
        });
        jPanel1.add(jLandlord);
        jLandlord.setBounds(79, 113, 111, 31);

        jTenant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTenant.setText("Tenant");
        jTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTenantActionPerformed(evt);
            }
        });
        jPanel1.add(jTenant);
        jTenant.setBounds(79, 208, 97, 31);

        jVisitor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jVisitor.setText("Visitor");
        jVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVisitorActionPerformed(evt);
            }
        });
        jPanel1.add(jVisitor);
        jVisitor.setBounds(339, 113, 89, 31);

        jCaretaker.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCaretaker.setText("Caretaker");
        jCaretaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaretakerActionPerformed(evt);
            }
        });
        jPanel1.add(jCaretaker);
        jCaretaker.setBounds(339, 208, 123, 31);

        jExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jExit.setText("Exit");
        jPanel1.add(jExit);
        jExit.setBounds(204, 278, 67, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\musyo\\Downloads\\architecture-3101110_640.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 550, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLandlordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLandlordActionPerformed
    
        Landlord_page s =new Landlord_page();
        s.setVisible(true);
    }//GEN-LAST:event_jLandlordActionPerformed

    private void jVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVisitorActionPerformed
        Visitor_page s= new Visitor_page();
        s.setVisible(true);
        
    }//GEN-LAST:event_jVisitorActionPerformed

    private void jTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTenantActionPerformed
        Tenant_page s=new Tenant_page();
        s.setVisible(true);
    }//GEN-LAST:event_jTenantActionPerformed

    private void jCaretakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaretakerActionPerformed
        Caretaker_page s=new Caretaker_page();
        s.setVisible(true);
    }//GEN-LAST:event_jCaretakerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCaretaker;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLandlord;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jTenant;
    private javax.swing.JButton jVisitor;
    // End of variables declaration//GEN-END:variables
}
